%Print.m
%Messages to print to screen after using the algorithm

if not_P == 0; disp('M matrix is a P-matrix'); 
elseif not_P == 1; disp('M matrix is not a P-matrix');
end

if Message_1 == 1
    x_disp = sprintf('Increase N_guess if you want to include all %d guesses generated by Guesses_master or Guesses_master_2',d0); disp(x_disp)
elseif Message_2 == 1
    x_disp = sprintf('More guesses made than are generated by the Guesses_master file used: %d versus %d. The excess guesses are random guesses of 0s and 1s.',N_guess,d0); disp(x_disp)
end